os: linux
sudo: false
language: python
python:
  - 2.7
  - 3.6
  - 3.7
install:
  - pip install -r requirements.in
  - pip install -r requirements-dev.in
script:
  - inv check
  - inv unittest
  - inv coverage
after_success:
  - coveralls
