os: linux
sudo: false
language: python
python:
  - 2.7
  - 3.6
  - 3.7
install:
  - pip install pipenv
  - pipenv install --deploy --dev --skip-lock
script:
  - inv check
  - inv unittest
  - inv coverage
after_success:
  - coveralls
