default_ssh_conf:
    user: root
    port: 22
    identityfile: ~/.ssh/id_rsa

host_type_default: 10.10.100
host_type_2: 192.168.1

ipmi_interval: 100

projects:
    default:
        src:  ~/PythonProjects/plum_tools
        dest: /home/seekplum/plum_tools
        exclude:
            - .idea
            - .vscode
            - '*.pyc'
            - '*.log'
        delete: 0
