default_ssh_conf:
    user: root
    port: 22
    identityfile: ~/.ssh/id_rsa

host_type_default: 10.10.100
host_type_2: 192.168.1

ipmi_interval: 100

projects:
    default:
        src:  ~/PythonProjects/qdata-mgr/src/
        dest: /home/sendoh/qdatamgr
        exclude:
            - .git
            - .idea
            - .vscode
            - '*.pyc'
            - '*.log'

        delete: 0
