#!/usr/bin/env bash
exit_code=0

print_error () {
    echo -e "\033[31m$1\033[0m"
}

print_ok () {
    echo -e "\033[32m$1\033[0m"
}

run_coverage() {
    desc="Run Coverage"
    echo ${desc}
    inv coverage
    exit_code=$?
    check ${desc}
}


check (){
    if [ ${exit_code} -ne 0 ]; then
        print_error "$* failed."
        exit ${exit_code}
    else
        print_ok "$* success"
    fi
}

main() {
    run_coverage
}

main

exit ${exit_code}

