name: Test

on:
  pull_request: {}
  push:
    branches: master
    tags: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev --skip-lock

      - run: inv check
      - run: inv unittest
      - run: inv coverage

  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . -t plum_tools:test

      - name: Smoke test docker image
        run: |
          docker run --rm plum_tools:test
