name: Test

on:
  pull_request: {}
  push:
    branches: master
    tags: "*"

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Setup Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install tools
        run: pip install invoke
      - name: Install dependencies
        run: inv install --dev
      - name: Code checker
        run: inv lint
      - name: Unittest
        run: inv test
